---
title: "Covid Plots"
author: "Anthony Gibbons"
date: "11/24/2020"
output: 
  pdf_document:
    number_sections: true
---

```{r setup, include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(extrafont)
source("covidplots-group.r")
```

# Introduction
```{r fig0, echo=FALSE, fig.cap="\\label{fig:fig0} Daily cases Globally to date", fig.height=4}
plotslist$WorldTotal$xn
```

```{r fig1, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig1} $x$-diagram for Ireland: the numbers of actually registered daily cases", fig.height=4}
plotslist$Ireland$xn
```

```{r fig2, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig2} $x$-diagram for Ireland: the numbers of actually registered daily cases", fig.height=4}
plotslist$Ireland$yn
```

```{r fig3, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig3} Comparison of the basic model with the actual data, Ireland ($x$-diagram)", fig.height=4}
plotslist$Ireland$basexn
```

```{r fig4, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig4} Comparison of the basic model with the actual data, Ireland ($x$-diagram)", fig.height=4}
plotslist$Ireland$baseyn
```

```{r fig5, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig5} Comparison of $x^*_n$, $x_n$ and $Cr^n$, Ireland", fig.height=4}
plotslist$Ireland$Crn
```

```{r fig6, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig6} Comparison of basic model with moving averages, Ireland", fig.height=4}
plotslist$Ireland$mavgx3
```

```{r fig7, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig7} Comparison of basic and periodic models with moving averages, Ireland", fig.height=4}
plotslist$Ireland$periodic
```


```{r fig8, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig8} Comparison of basic and periodic models with HoltWinters model, Ireland", fig.height=4}
plotslist$Ireland$hw
```

```{r fig9, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig9} Comparison of Cumulative basic and periodic models with HoltWinters Prediction, Ireland", fig.height=4}
plotslist$Ireland$hwy
```


```{r fig10, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig10} Comparison of basic and periodic models with ARIMA model, Ireland", fig.height=4}
plotslist$Ireland$arima
```

```{r fig11, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig11} Comparison of Cumulative basic and periodic models with ARIMA model, Ireland", fig.height=4}
plotslist$Ireland$arimay
```

```{r IreHwArima, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:IreHwArima} Comparison of HoltWinters and ARIMA models, Ireland", fig.height=4}
plotslist$Ireland$hwarima
```

```{r fig12, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig12} Comparison of basic and periodic models with Neural Network model, Ireland", fig.height=4}
plotslist$Ireland$nn
```

```{r fig13, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig13} Comparison of Cumulative basic and periodic models with Neural Network model, Ireland", fig.height=4}
plotslist$Ireland$nny
```




```{r fig3Italy, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig3Italy} Comparison of the basic model with the actual data, Italy ($x$-diagram)", fig.height=4}
plotslist$Italy$basexn
```

```{r fig4Italy, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig4Italy} Comparison of the basic model with the actual data, Italy ($x$-diagram)", fig.height=4}
plotslist$Italy$baseyn
```

```{r fig7Italy, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig7Italy} Comparison of basic and periodic models with moving averages, Italy", fig.height=4}
plotslist$Italy$periodic
```

```{r fig8Italy, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig8Italy} Comparison of basic and periodic models with HoltWinters model, Italy", fig.height=4}
plotslist$Italy$hw
```

```{r fig10Italy, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig10Italy} Comparison of basic and periodic models with ARIMA model, Italy", fig.height=4}
plotslist$Italy$arima
```

```{r ItaHwArima, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:ItaHwArima} Comparison of HoltWinters and ARIMA models, Italy", fig.height=4}
plotslist$Italy$hwarima
```


```{r fig12Italy, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig12Italy} Comparison of basic and periodic models with Neural Network model, Italy", fig.height=4}
plotslist$Italy$nn
```


```{r fig3USA, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig3USA} Comparison of the basic model with the actual data, USA ($x$-diagram)", fig.height=4}
plotslist$USA$basexn
```

```{r fig4USA, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig4USA} Comparison of the basic model with the actual data, USA ($x$-diagram)", fig.height=4}
plotslist$USA$baseyn
```

```{r fig7USA, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig7USA} Comparison of basic and periodic models with moving averages, USA", fig.height=4}
plotslist$USA$periodic
```

```{r fig8USA, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig8USA} Comparison of basic and periodic models with HoltWinters model, USA", fig.height=4}
plotslist$USA$hw
```

```{r fig10USA, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig10USA} Comparison of basic and periodic models with ARIMA model, USA", fig.height=4}
plotslist$USA$arima
```

```{r UsaHwArima, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:UsaHwArima} Comparison of HoltWinters and ARIMA models, USA", fig.height=4}
plotslist$USA$hwarima
```

```{r fig12USA, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:fig12USA} Comparison of basic and periodic models with Neural Network model, USA", fig.height=4}
plotslist$USA$nn
```


```{r multiItalyxn, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:multiItalyxn} A multi-phase periodic model for Italy (x-diagram)", fig.height=4}
multilist$Italy$perxn
```

```{r multiItalyyn, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:multiItalyyn} A multi-phase periodic model for Italy (y-diagram)", fig.height=4}
multilist$Italy$peryn
```


```{r multiIrelandxn, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:multiIrelandxn} A multi-phase periodic model for Ireland (x-diagram)", fig.height=4}
multilist$Ireland$perxn
```

```{r multiIrelandyn, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:multiIrelandyn} A multi-phase periodic model for Ireland (y-diagram)", fig.height=4}
multilist$Ireland$peryn
```


```{r multiUSAxn, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:multiUSAxn} A multi-phase periodic model for the USA (x-diagram)", fig.height=4}
multilist$USA$perxn
```

```{r multiUSAyn, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:multiUSAyn} A multi-phase periodic model for the USA (y-diagram)", fig.height=4}
multilist$USA$peryn
```


```{r compIreUK, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:compIreUK} A Comparison of the cumulative number of cases for 14 days per 100,000 of the populaiton - Ireland vs UK", fig.height=4}
comparelist$IreUK
```

```{r compIreUS, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:compIreUS} A Comparison of the cumulative number of cases for 14 days per 100,000 of the populaiton - Ireland vs USA", fig.height=4}
comparelist$IreUS
```

```{r compIreIta, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:compIreIta} A Comparison of the cumulative number of cases for 14 days per 100,000 of the populaiton - Ireland vs Italy", fig.height=4}
comparelist$IreIta
```

```{r compIreNl, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:compIreNl} A Comparison of the cumulative number of cases for 14 days per 100,000 of the populaiton - Ireland vs Netherlands", fig.height=4}
comparelist$IreNl
```

```{r compIreIce, echo=FALSE, warning = FALSE, fig.cap="\\label{fig:compIreIce} A Comparison of the cumulative number of cases for 14 days per 100,000 of the populaiton - Ireland vs Iceland", fig.height=4}
comparelist$IreIce
```