---
title: "Map Plots"
author: "Anthony Gibbons"
date: "11/24/2020"
geometry: margin=0.5cm
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source("countymap.r")
```

```{r WorldByCountry, echo=FALSE, fig.cap="\\label{fig:WorldByCountry} Cases per 100,000 of country population, Global", fig.height=5}
worldplot$blank
```

```{r EuropeByCountry, echo=FALSE, fig.cap="\\label{fig:EuropeByCountry} Cases per 100,000 of country population, Europe", fig.height=5}
worldplot$europe
```

```{r IreByCounty, echo=FALSE, fig.cap="\\label{fig:IreByCounty} Cases per 100,000 of county population", fig.height=6}
countyplotlist$blank
```

```{r repIreByCounty, echo=FALSE, fig.cap="\\label{fig:repIreByCounty} Cases per 100,000 of county population", fig.height=6}
countyplotlist$rep
```

```{r nmIreByCounty, echo=FALSE, fig.cap="\\label{fig:nmIreByCounty} Cases per 100,000 of county population", fig.height=6}
countyplotlist$names
```

```{r fourteenIreByCounty, echo=FALSE, fig.cap="\\label{fig:fourteenIreByCounty} Total Cases in Ireland by county over the last 14 days", fig.height=6}
countyplotlist$fourteendaycases
```